workspace = { members = ["mylib"] }
[package]
name = "c24_modules"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mylib = { path = "../c24_modules/mylib" }
